---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="cjsteel"
  matrix:
    - image="fedora"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all
