---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: "${namespace:-robertdebock-}${image:-ubuntu}-${TOX_ENVNAME:-default}"
    image: "${namespace:-robertdebock}/${image:-ubuntu}:${tag:-rolling}"
    command: sh -c "while true ; do sleep 30 ; done"
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
scenario:
  name: default
